# Generated by Django 4.2.6 on 2023-10-14 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wicht the object was last modified', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre cliente')),
                ('apellido', models.CharField(max_length=30, unique=True)),
                ('dpi', models.CharField(max_length=13, unique=True)),
                ('pasaporte', models.CharField(max_length=11, unique=True)),
                ('nit', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=40, verbose_name='direccion cliente')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='nacionalidad cliente')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wicht the object was last modified', verbose_name='modified at')),
                ('tipo', models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('triple', 'Triple'), ('matrimonial', 'Matrimonial')], max_length=20)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wicht the object was last modified', verbose_name='modified at')),
                ('tipo_cliente', models.CharField(max_length=40)),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
                ('adulto', models.PositiveBigIntegerField()),
                ('nino', models.PositiveBigIntegerField()),
                ('edad_nino', models.PositiveBigIntegerField()),
                ('desayuno_buffete', models.PositiveBigIntegerField()),
                ('dias_renta_auto', models.PositiveBigIntegerField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
