# Generated by Django 4.2.6 on 2023-10-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wicht the object was last modified', verbose_name='modified at')),
                ('tipo_cliente', models.CharField(max_length=40)),
                ('fecha_hora_entrada', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField()),
                ('adulto', models.PositiveBigIntegerField()),
                ('nino', models.PositiveBigIntegerField()),
                ('edad_nino', models.PositiveBigIntegerField()),
                ('desayuno_buffete', models.PositiveBigIntegerField()),
                ('dias_renta_auto', models.PositiveBigIntegerField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
