# Generated by Django 4.2.6 on 2023-10-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservacion_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='forma_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('tarjeta_credito', 'Tarjeta_Credito')], default='Contado', max_length=20),
        ),
    ]
