# Generated by Django 4.2.6 on 2023-10-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservacion_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('triple', 'Triple'), ('matrimonial', 'Matrimonial')], default='Simple', max_length=20),
        ),
    ]
